// Phase 4 — Communication & Payment seed data
import type {
  PaymentGateway, PaymentTransaction, PaymentWebhook, PaymentLink,
  SmsProviderConfig, SmsTemplate, SmsMessage, SmsCampaign,
  EmailProviderConfig, EmailTemplate, EmailMessage, EmailCampaign,
  PushProviderConfig, PushSubscriber, PushCampaign,
  ESignProviderConfig, ESignDocument, ESignSigner, ESignRequest, ESignAuditEvent,
} from '@/types';

const today = '2026-06-02';
const isoNow = '2026-06-02T10:30:00Z';

// ─────────────────────────────────────────────
// 4.1 Payment Gateways
// ─────────────────────────────────────────────
export const seedPaymentGateways: PaymentGateway[] = [
  {
    id: 'pg-1', company_id: 'comp-1', provider: 'hyperpay', display_name: 'HyperPay (Primary)',
    mode: 'live', status: 'active', merchant_id: 'MERCH_HYP_2026_001',
    api_key_masked: 'pk_live_••••••••a4f2', webhook_secret_masked: 'whsec_••••••••91c8',
    supported_methods: ['mada', 'visa', 'mastercard', 'amex', 'applepay'],
    transaction_fee_percent: 2.4, transaction_fee_fixed: 0.5, currency: 'QAR',
    settlement_days: 2, is_default: true,
    created_at: '2025-08-15', updated_at: today, notes: 'البوابة الرئيسية لمعاملات الإيجار',
  },
  {
    id: 'pg-2', company_id: 'comp-1', provider: 'moyasar', display_name: 'Moyasar (Saudi)',
    mode: 'live', status: 'active', merchant_id: 'MOY_SA_8821',
    api_key_masked: 'pk_test_••••••••3d9e', webhook_secret_masked: 'whsec_••••••••b2a1',
    supported_methods: ['mada', 'visa', 'mastercard', 'applepay', 'stcpay'],
    transaction_fee_percent: 2.1, transaction_fee_fixed: 1.0, currency: 'QAR',
    settlement_days: 1, is_default: false,
    created_at: '2025-10-20', updated_at: today, notes: 'دعم إضافي لعملاء STC Pay',
  },
  {
    id: 'pg-3', company_id: 'comp-1', provider: 'paytabs', display_name: 'PayTabs (Backup)',
    mode: 'test', status: 'inactive', merchant_id: 'PT_BACKUP_001',
    api_key_masked: 'sk_test_••••••••1f7c', webhook_secret_masked: 'whsec_••••••••44de',
    supported_methods: ['visa', 'mastercard', 'amex', 'benefit'],
    transaction_fee_percent: 2.75, transaction_fee_fixed: 0.3, currency: 'QAR',
    settlement_days: 3, is_default: false,
    created_at: '2026-01-05', updated_at: today, notes: 'احتياطي - وضع الاختبار',
  },
  {
    id: 'pg-4', company_id: 'comp-1', provider: 'tap', display_name: 'Tap Payments (UAE)',
    mode: 'live', status: 'active', merchant_id: 'TAP_UAE_4421',
    api_key_masked: 'sk_live_••••••••88ae', webhook_secret_masked: 'whsec_••••••••cc52',
    supported_methods: ['visa', 'mastercard', 'amex', 'knet', 'omannet', 'applepay'],
    transaction_fee_percent: 2.6, transaction_fee_fixed: 0.6, currency: 'QAR',
    settlement_days: 2, is_default: false,
    created_at: '2026-03-12', updated_at: today, notes: 'دعم الكويت وعُمان',
  },
];

// ─────────────────────────────────────────────
// 4.1 Payment Transactions
// ─────────────────────────────────────────────
export const seedPaymentTransactions: PaymentTransaction[] = [
  { id: 'pt-1', company_id: 'comp-1', gateway_id: 'pg-1', gateway_provider: 'hyperpay',
    reference: 'INV-2026-001', gateway_reference: 'hp_5f8a3c1d9e2b',
    invoice_id: 'inv-4', tenant_id: 'tnt-1', amount: 60000, currency: 'QAR',
    fee: 1445, net_amount: 58555, method: 'mada', card_last4: '4581', card_brand: 'mada',
    status: 'settled', customer_name: 'أحمد محمد العمري', customer_email: 'ahmed@email.com',
    customer_phone: '+97450001122', description: 'دفعة إيجار يناير 2026 - A-101',
    ip_address: '188.50.12.44', error_code: '', error_message: '',
    initiated_at: '2026-01-10T08:14:22Z', authorized_at: '2026-01-10T08:14:31Z',
    captured_at: '2026-01-10T08:14:32Z', settled_at: '2026-01-12T08:00:00Z',
    refunded_at: '', refund_amount: 0, refund_reason: '', metadata: '{}' },
  { id: 'pt-2', company_id: 'comp-1', gateway_id: 'pg-2', gateway_provider: 'moyasar',
    reference: 'INV-2026-002', gateway_reference: 'ms_7b2e9f4a1c08',
    invoice_id: 'inv-5', tenant_id: 'tnt-2', amount: 57600, currency: 'QAR',
    fee: 1209.6, net_amount: 56390.4, method: 'visa', card_last4: '4242', card_brand: 'visa',
    status: 'captured', customer_name: 'سارة خالد القحطاني', customer_email: 'sara@email.com',
    customer_phone: '+97450002233', description: 'دفعة إيجار مارس 2026 - A-102',
    ip_address: '94.200.5.122', error_code: '', error_message: '',
    initiated_at: '2026-03-08T11:22:18Z', authorized_at: '2026-03-08T11:22:25Z',
    captured_at: '2026-03-08T11:22:26Z', settled_at: '',
    refunded_at: '', refund_amount: 0, refund_reason: '', metadata: '{}' },
  { id: 'pt-3', company_id: 'comp-1', gateway_id: 'pg-1', gateway_provider: 'hyperpay',
    reference: 'INV-2026-003', gateway_reference: 'hp_3d8a7b9e4c12',
    invoice_id: 'inv-6', tenant_id: 'tnt-3', amount: 30000, currency: 'QAR',
    fee: 720, net_amount: 29280, method: 'mastercard', card_last4: '5555', card_brand: 'mastercard',
    status: 'settled', customer_name: 'شركة النور التجارية', customer_email: 'info@alnoor.com',
    customer_phone: '+97450003344', description: 'دفعة إيجار يونيو 2026 - B-201',
    ip_address: '188.50.45.78', error_code: '', error_message: '',
    initiated_at: '2026-06-05T14:08:11Z', authorized_at: '2026-06-05T14:08:18Z',
    captured_at: '2026-06-05T14:08:19Z', settled_at: '2026-06-07T08:00:00Z',
    refunded_at: '', refund_amount: 0, refund_reason: '', metadata: '{}' },
  { id: 'pt-4', company_id: 'comp-1', gateway_id: 'pg-4', gateway_provider: 'tap',
    reference: 'INV-2026-001-1', gateway_reference: 'tap_99f8e7d6c5b4',
    invoice_id: 'inv-4', tenant_id: 'tnt-1', amount: 15000, currency: 'QAR',
    fee: 390, net_amount: 14610, method: 'applepay', card_last4: '', card_brand: 'applepay',
    status: 'awaiting_3ds', customer_name: 'أحمد محمد العمري', customer_email: 'ahmed@email.com',
    customer_phone: '+97450001122', description: 'دفعة جزئية - A-101',
    ip_address: '188.50.12.44', error_code: '', error_message: '',
    initiated_at: '2026-06-01T09:45:00Z', authorized_at: '', captured_at: '',
    settled_at: '', refunded_at: '', refund_amount: 0, refund_reason: '', metadata: '{}' },
  { id: 'pt-5', company_id: 'comp-1', gateway_id: 'pg-1', gateway_provider: 'hyperpay',
    reference: 'INV-2025-003', gateway_reference: 'hp_2c1a4b9e8f73',
    invoice_id: 'inv-3', tenant_id: 'tnt-3', amount: 30000, currency: 'QAR',
    fee: 720, net_amount: 29280, method: 'visa', card_last4: '1111', card_brand: 'visa',
    status: 'refunded', customer_name: 'شركة النور التجارية', customer_email: 'info@alnoor.com',
    customer_phone: '+97450003344', description: 'استرجاع - عقد ملغى',
    ip_address: '188.50.45.78', error_code: '', error_message: '',
    initiated_at: '2025-09-15T10:00:00Z', authorized_at: '2025-09-15T10:00:10Z',
    captured_at: '2025-09-15T10:00:11Z', settled_at: '2025-09-17T08:00:00Z',
    refunded_at: '2026-04-22T13:15:00Z', refund_amount: 30000, refund_reason: 'إلغاء عقد إيجار', metadata: '{}' },
  { id: 'pt-6', company_id: 'comp-1', gateway_id: 'pg-1', gateway_provider: 'hyperpay',
    reference: 'INV-2025-008', gateway_reference: 'hp_5e2d8c1f7a90',
    invoice_id: 'inv-4', tenant_id: 'tnt-4', amount: 36000, currency: 'QAR',
    fee: 864, net_amount: 35136, method: 'mada', card_last4: '9999', card_brand: 'mada',
    status: 'failed', customer_name: 'فهد عبدالله الشمري', customer_email: 'fahad@email.com',
    customer_phone: '+97450004455', description: 'دفعة إيجار Q1 2025',
    ip_address: '94.200.10.5', error_code: 'INSUFFICIENT_FUNDS', error_message: 'الرصيد غير كافٍ',
    initiated_at: '2025-02-20T15:30:00Z', authorized_at: '2025-02-20T15:30:08Z',
    captured_at: '', settled_at: '',
    refunded_at: '', refund_amount: 0, refund_reason: '', metadata: '{}' },
  { id: 'pt-7', company_id: 'comp-1', gateway_id: 'pg-2', gateway_provider: 'moyasar',
    reference: 'INV-2026-005', gateway_reference: 'ms_4a7b9c2d1e8f',
    invoice_id: 'inv-4', tenant_id: 'tnt-1', amount: 5000, currency: 'QAR',
    fee: 111, net_amount: 4889, method: 'stcpay', card_last4: '', card_brand: 'stcpay',
    status: 'partially_refunded', customer_name: 'أحمد محمد العمري', customer_email: 'ahmed@email.com',
    customer_phone: '+97450001122', description: 'غرامة تأخير',
    ip_address: '188.50.12.44', error_code: '', error_message: '',
    initiated_at: '2026-04-12T16:20:00Z', authorized_at: '2026-04-12T16:20:11Z',
    captured_at: '2026-04-12T16:20:12Z', settled_at: '2026-04-14T08:00:00Z',
    refunded_at: '2026-05-01T10:00:00Z', refund_amount: 1000, refund_reason: 'استرداد جزء من الغرامة', metadata: '{}' },
  { id: 'pt-8', company_id: 'comp-1', gateway_id: 'pg-1', gateway_provider: 'hyperpay',
    reference: 'INV-2026-007', gateway_reference: 'hp_8c9d0e1f2a3b',
    invoice_id: 'inv-5', tenant_id: 'tnt-2', amount: 8000, currency: 'QAR',
    fee: 192, net_amount: 7808, method: 'benefit', card_last4: '7777', card_brand: 'benefit',
    status: 'initiated', customer_name: 'سارة خالد القحطاني', customer_email: 'sara@email.com',
    customer_phone: '+97450002233', description: 'دفعة صيانة',
    ip_address: '94.200.5.122', error_code: '', error_message: '',
    initiated_at: '2026-06-02T09:15:00Z', authorized_at: '', captured_at: '',
    settled_at: '', refunded_at: '', refund_amount: 0, refund_reason: '', metadata: '{}' },
];

// ─────────────────────────────────────────────
// 4.1 Payment Webhooks
// ─────────────────────────────────────────────
export const seedPaymentWebhooks: PaymentWebhook[] = [
  { id: 'pwh-1', company_id: 'comp-1', gateway_id: 'pg-1', gateway_provider: 'hyperpay',
    event: 'payment.captured', status: 'processed',
    payload_json: '{"id":"hp_5f8a3c1d9e2b","status":"captured","amount":60000,"currency":"QAR","reference":"INV-2026-001"}',
    signature: 'sha256=•••••88a1', signature_valid: true, transaction_id: 'pt-1',
    received_at: '2026-01-10T08:14:35Z', processed_at: '2026-01-10T08:14:36Z',
    retry_count: 0, last_error: '', ip_address: '54.187.205.235' },
  { id: 'pwh-2', company_id: 'comp-1', gateway_id: 'pg-1', gateway_provider: 'hyperpay',
    event: 'payout.settled', status: 'processed',
    payload_json: '{"id":"hp_5f8a3c1d9e2b","settlement_id":"set_8821","net_amount":58555}',
    signature: 'sha256=•••••42de', signature_valid: true, transaction_id: 'pt-1',
    received_at: '2026-01-12T08:00:12Z', processed_at: '2026-01-12T08:00:14Z',
    retry_count: 0, last_error: '', ip_address: '54.187.205.235' },
  { id: 'pwh-3', company_id: 'comp-1', gateway_id: 'pg-2', gateway_provider: 'moyasar',
    event: 'payment.refunded', status: 'processed',
    payload_json: '{"id":"ms_4a7b9c2d1e8f","refund_id":"rf_91a","amount":1000}',
    signature: 'sha256=•••••cc52', signature_valid: true, transaction_id: 'pt-7',
    received_at: '2026-05-01T10:00:08Z', processed_at: '2026-05-01T10:00:10Z',
    retry_count: 0, last_error: '', ip_address: '52.211.95.122' },
  { id: 'pwh-4', company_id: 'comp-1', gateway_id: 'pg-1', gateway_provider: 'hyperpay',
    event: 'payment.dispute.created', status: 'retrying',
    payload_json: '{"dispute_id":"dsp_4421","transaction_id":"hp_2c1a4b9e8f73","reason":"fraud"}',
    signature: 'sha256=•••••invalid', signature_valid: false, transaction_id: 'pt-5',
    received_at: '2026-05-28T14:00:00Z', processed_at: '',
    retry_count: 3, last_error: 'توقيع غير صالح - في انتظار إعادة الإرسال',
    ip_address: '54.187.205.235' },
  { id: 'pwh-5', company_id: 'comp-1', gateway_id: 'pg-4', gateway_provider: 'tap',
    event: 'payment.failed', status: 'failed',
    payload_json: '{"id":"tap_99f8e7d6c5b4","error":"3DS_TIMEOUT"}',
    signature: 'sha256=•••••1c8b', signature_valid: true, transaction_id: 'pt-4',
    received_at: '2026-06-01T09:46:30Z', processed_at: '',
    retry_count: 0, last_error: 'انتهت مهلة 3D Secure',
    ip_address: '52.9.110.42' },
];

// ─────────────────────────────────────────────
// 4.1 Payment Links
// ─────────────────────────────────────────────
export const seedPaymentLinks: PaymentLink[] = [
  { id: 'pl-1', company_id: 'comp-1', gateway_id: 'pg-1', reference: 'INV-2026-001',
    title: 'دفعة إيجار A-101 - يناير 2026', description: 'إيجار شهر يناير 2026 للوحدة A-101',
    amount: 60000, currency: 'QAR', url_slug: 'pay-a101-jan-2026',
    customer_name: 'أحمد محمد العمري', customer_phone: '+97450001122',
    customer_email: 'ahmed@email.com',
    expires_at: '2026-02-15', status: 'paid', paid_at: '2026-01-10T08:14:32Z',
    paid_transaction_id: 'pt-1', view_count: 4, created_at: '2026-01-01', notes: '' },
  { id: 'pl-2', company_id: 'comp-1', gateway_id: 'pg-2', reference: 'INV-2026-002',
    title: 'دفعة إيجار A-102 - مارس 2026', description: 'إيجار شهر مارس 2026',
    amount: 57600, currency: 'QAR', url_slug: 'pay-a102-mar-2026',
    customer_name: 'سارة خالد القحطاني', customer_phone: '+97450002233',
    customer_email: 'sara@email.com',
    expires_at: '2026-04-15', status: 'active', paid_at: '',
    paid_transaction_id: '', view_count: 12, created_at: '2026-03-01', notes: '' },
  { id: 'pl-3', company_id: 'comp-1', gateway_id: 'pg-1', reference: 'INV-2026-008',
    title: 'دفعة صيانة - C-301', description: 'تكاليف إصلاح السباكة',
    amount: 1500, currency: 'QAR', url_slug: 'maint-c301',
    customer_name: '', customer_phone: '', customer_email: '',
    expires_at: '2026-07-01', status: 'active', paid_at: '',
    paid_transaction_id: '', view_count: 0, created_at: today, notes: '' },
];

// ─────────────────────────────────────────────
// 4.2 SMS Providers
// ─────────────────────────────────────────────
export const seedSmsProviders: SmsProviderConfig[] = [
  { id: 'sms-prov-1', company_id: 'comp-1', provider: 'unifonic', display_name: 'Unifonic (MENA Primary)',
    sender_id: 'AQARI-ERP', status: 'active', api_key_masked: 'uni_live_••••••••7d8c',
    balance: 4250, balance_currency: 'QAR', cost_per_sms: 0.045,
    is_default: true, unicode_supported: true,
    created_at: '2025-08-15', updated_at: today },
  { id: 'sms-prov-2', company_id: 'comp-1', provider: 'twilio', display_name: 'Twilio (Global Backup)',
    sender_id: '+97444001122', status: 'active', api_key_masked: 'SK••••••••b2a1',
    balance: 1280, balance_currency: 'QAR', cost_per_sms: 0.052,
    is_default: false, unicode_supported: true,
    created_at: '2025-09-20', updated_at: today },
  { id: 'sms-prov-3', company_id: 'comp-1', provider: 'msegat', display_name: 'Msegat (Saudi)',
    sender_id: 'AQARI-SA', status: 'inactive', api_key_masked: 'ms_••••••••3e8a',
    balance: 850, balance_currency: 'QAR', cost_per_sms: 0.038,
    is_default: false, unicode_supported: true,
    created_at: '2026-01-10', updated_at: today },
];

// ─────────────────────────────────────────────
// 4.2 SMS Templates
// ─────────────────────────────────────────────
export const seedSmsTemplates: SmsTemplate[] = [
  { id: 'smst-1', company_id: 'comp-1', name: 'تذكير دفع الإيجار', category: 'rent_due', language: 'ar',
    body: 'عزيزي {{tenant_name}}، نود تذكيركم بأن دفعة الإيجار المستحقة على الوحدة {{unit_number}} بمبلغ {{amount}} ر.ق تستحق في {{due_date}}. شكراً - إدارة عقاري',
    variables: ['tenant_name', 'unit_number', 'amount', 'due_date'],
    status: 'active', created_at: '2025-08-15', updated_at: today, notes: '' },
  { id: 'smst-2', company_id: 'comp-1', name: 'إيجار متأخر', category: 'rent_overdue', language: 'ar',
    body: 'تنبيه: عزيزي {{tenant_name}}، دفعة الإيجار للوحدة {{unit_number}} متأخرة منذ {{days_overdue}} يوم. يرجى السداد لتفادي غرامات التأخير.',
    variables: ['tenant_name', 'unit_number', 'days_overdue'],
    status: 'active', created_at: '2025-08-15', updated_at: today, notes: '' },
  { id: 'smst-3', company_id: 'comp-1', name: 'استلام دفعة', category: 'rent_received', language: 'ar',
    body: 'شكراً {{tenant_name}}، تم استلام دفعة الإيجار بمبلغ {{amount}} ر.ق. رقم الإيصال: {{receipt_number}}.',
    variables: ['tenant_name', 'amount', 'receipt_number'],
    status: 'active', created_at: '2025-08-20', updated_at: today, notes: '' },
  { id: 'smst-4', company_id: 'comp-1', name: 'توقيع عقد إيجار', category: 'lease_signed', language: 'ar',
    body: 'مرحباً {{tenant_name}}، تم توقيع عقد الإيجار {{contract_number}} بنجاح. تاريخ البدء: {{start_date}}.',
    variables: ['tenant_name', 'contract_number', 'start_date'],
    status: 'active', created_at: '2025-08-20', updated_at: today, notes: '' },
  { id: 'smst-5', company_id: 'comp-1', name: 'تحديث صيانة', category: 'maintenance_update', language: 'ar',
    body: 'تحديث صيانة: طلب الصيانة #{{request_id}} للوحدة {{unit_number}} - {{status}}. {{notes}}',
    variables: ['request_id', 'unit_number', 'status', 'notes'],
    status: 'active', created_at: '2025-09-01', updated_at: today, notes: '' },
  { id: 'smst-6', company_id: 'comp-1', name: 'تجديد عقد', category: 'lease_renewal', language: 'ar',
    body: 'عزيزي {{tenant_name}}، عقد الإيجار {{contract_number}} ينتهي في {{end_date}}. هل ترغب في التجديد؟',
    variables: ['tenant_name', 'contract_number', 'end_date'],
    status: 'active', created_at: '2025-09-15', updated_at: today, notes: '' },
  { id: 'smst-7', company_id: 'comp-1', name: 'رمز تحقق', category: 'verification', language: 'ar',
    body: 'رمز التحقق الخاص بك: {{code}} - صالح لمدة 5 دقائق. لا تشاركه مع أحد.',
    variables: ['code'], status: 'active', created_at: '2025-10-01', updated_at: today, notes: '' },
];

// ─────────────────────────────────────────────
// 4.2 SMS Messages
// ─────────────────────────────────────────────
export const seedSmsMessages: SmsMessage[] = [
  { id: 'sms-1', company_id: 'comp-1', provider_id: 'sms-prov-1', provider: 'unifonic',
    template_id: 'smst-1', campaign_id: '',
    to_phone: '+97450001122', to_name: 'أحمد محمد العمري',
    body: 'عزيزي أحمد محمد العمري، نود تذكيركم بأن دفعة الإيجار المستحقة على الوحدة A-101 بمبلغ 60000 ر.ق تستحق في 2026-01-15.',
    status: 'delivered', segments: 1, cost: 0.045, sender_id: 'AQARI-ERP',
    gateway_message_id: 'uni_msg_8821a', sent_at: '2026-01-05T08:00:00Z',
    delivered_at: '2026-01-05T08:00:03Z', failed_at: '',
    error_code: '', error_message: '', direction: 'outbound',
    related_entity_type: 'invoice', related_entity_id: 'inv-4',
    created_at: '2026-01-05T08:00:00Z' },
  { id: 'sms-2', company_id: 'comp-1', provider_id: 'sms-prov-1', provider: 'unifonic',
    template_id: 'smst-3', campaign_id: '',
    to_phone: '+97450001122', to_name: 'أحمد محمد العمري',
    body: 'شكراً أحمد محمد العمري، تم استلام دفعة الإيجار بمبلغ 60000 ر.ق. رقم الإيصال: RCP-2026-001.',
    status: 'delivered', segments: 1, cost: 0.045, sender_id: 'AQARI-ERP',
    gateway_message_id: 'uni_msg_8821b', sent_at: '2026-01-10T08:14:35Z',
    delivered_at: '2026-01-10T08:14:37Z', failed_at: '',
    error_code: '', error_message: '', direction: 'outbound',
    related_entity_type: 'receipt', related_entity_id: 'rcp-1',
    created_at: '2026-01-10T08:14:35Z' },
  { id: 'sms-3', company_id: 'comp-1', provider_id: 'sms-prov-2', provider: 'twilio',
    template_id: 'smst-2', campaign_id: 'smsc-1',
    to_phone: '+97450004455', to_name: 'فهد عبدالله الشمري',
    body: 'تنبيه: عزيزي فهد عبدالله الشمري، دفعة الإيجار للوحدة A-301 متأخرة منذ 45 يوم. يرجى السداد.',
    status: 'failed', segments: 1, cost: 0.052, sender_id: '+97444001122',
    gateway_message_id: 'tw_msg_fail_44', sent_at: '2026-05-20T10:00:00Z',
    delivered_at: '', failed_at: '2026-05-20T10:00:05Z',
    error_code: '21610', error_message: 'الرقم محظور من قبل المستلم',
    direction: 'outbound',
    related_entity_type: 'invoice', related_entity_id: 'inv-4',
    created_at: '2026-05-20T10:00:00Z' },
  { id: 'sms-4', company_id: 'comp-1', provider_id: 'sms-prov-1', provider: 'unifonic',
    template_id: 'smst-5', campaign_id: '',
    to_phone: '+97450003344', to_name: 'شركة النور التجارية',
    body: 'تحديث صيانة: طلب الصيانة #MNT-2026-014 للوحدة B-201 - تم إسناد العمل لفني أحمد.',
    status: 'delivered', segments: 1, cost: 0.045, sender_id: 'AQARI-ERP',
    gateway_message_id: 'uni_msg_8822c', sent_at: '2026-05-25T14:30:00Z',
    delivered_at: '2026-05-25T14:30:04Z', failed_at: '',
    error_code: '', error_message: '', direction: 'outbound',
    related_entity_type: 'maintenance', related_entity_id: 'mnt-1',
    created_at: '2026-05-25T14:30:00Z' },
  { id: 'sms-5', company_id: 'comp-1', provider_id: 'sms-prov-1', provider: 'unifonic',
    template_id: 'smst-7', campaign_id: '',
    to_phone: '+97450002233', to_name: 'سارة خالد القحطاني',
    body: 'رمز التحقق الخاص بك: 482913 - صالح لمدة 5 دقائق. لا تشاركه مع أحد.',
    status: 'delivered', segments: 1, cost: 0.045, sender_id: 'AQARI-ERP',
    gateway_message_id: 'uni_msg_8823', sent_at: '2026-06-01T16:00:00Z',
    delivered_at: '2026-06-01T16:00:02Z', failed_at: '',
    error_code: '', error_message: '', direction: 'outbound',
    related_entity_type: 'user', related_entity_id: 'user-2',
    created_at: '2026-06-01T16:00:00Z' },
  { id: 'sms-6', company_id: 'comp-1', provider_id: 'sms-prov-1', provider: 'unifonic',
    template_id: '', campaign_id: 'smsc-2',
    to_phone: '+97450001122', to_name: 'أحمد محمد العمري',
    body: 'تذكير: عقود الإيجار تنتهي خلال 60 يوم. يرجى مراجعة إدارة العقود.',
    status: 'sent', segments: 1, cost: 0.045, sender_id: 'AQARI-ERP',
    gateway_message_id: 'uni_msg_8824', sent_at: '2026-06-02T08:00:00Z',
    delivered_at: '', failed_at: '',
    error_code: '', error_message: '', direction: 'outbound',
    related_entity_type: 'campaign', related_entity_id: 'smsc-2',
    created_at: '2026-06-02T08:00:00Z' },
];

// ─────────────────────────────────────────────
// 4.2 SMS Campaigns
// ─────────────────────────────────────────────
export const seedSmsCampaigns: SmsCampaign[] = [
  { id: 'smsc-1', company_id: 'comp-1', name: 'تذكير المتأخرات - مايو 2026',
    template_id: 'smst-2', audience_type: 'overdue_tenants', audience_count: 12,
    recipient_list_json: '["tnt-1","tnt-4","tnt-3"]',
    scheduled_at: '', sent_at: '2026-05-20T10:00:00Z',
    status: 'completed', delivered_count: 10, failed_count: 2, total_cost: 0.52,
    created_by: 'نورة الدوسري', created_at: '2026-05-19', notes: 'حملة المتأخرات الشهرية' },
  { id: 'smsc-2', company_id: 'comp-1', name: 'تنبيه تجديد العقود',
    template_id: 'smst-6', audience_type: 'all_tenants', audience_count: 5,
    recipient_list_json: '[]',
    scheduled_at: '', sent_at: '2026-06-02T08:00:00Z',
    status: 'sending', delivered_count: 1, failed_count: 0, total_cost: 0.045,
    created_by: 'محمد العتيبي', created_at: '2026-06-01', notes: 'العقود التي تنتهي خلال 60 يوم' },
  { id: 'smsc-3', company_id: 'comp-1', name: 'إعلان صيانة دورية',
    template_id: '', audience_type: 'all_tenants', audience_count: 5,
    recipient_list_json: '[]',
    scheduled_at: '2026-06-15T09:00:00Z', sent_at: '',
    status: 'scheduled', delivered_count: 0, failed_count: 0, total_cost: 0,
    created_by: 'سارة القحطاني', created_at: '2026-06-01', notes: 'صيانة المصاعد يوم 20 يونيو' },
];

// ─────────────────────────────────────────────
// 4.3 Email Providers
// ─────────────────────────────────────────────
export const seedEmailProviders: EmailProviderConfig[] = [
  { id: 'email-prov-1', company_id: 'comp-1', provider: 'resend', display_name: 'Resend (Primary)',
    from_address: 'noreply@aqari-erp.com', from_name: 'عقاري ERP',
    reply_to: 'support@aqari-erp.com', status: 'active',
    api_key_masked: 're_••••••••a4f2', daily_quota: 10000, daily_sent: 1248,
    is_default: true, track_opens: true, track_clicks: true,
    created_at: '2025-08-15', updated_at: today },
  { id: 'email-prov-2', company_id: 'comp-1', provider: 'sendgrid', display_name: 'SendGrid (Enterprise)',
    from_address: 'billing@aqari-erp.com', from_name: 'Aqari Billing',
    reply_to: 'billing@aqari-erp.com', status: 'active',
    api_key_masked: 'SG.••••••••91c8', daily_quota: 50000, daily_sent: 0,
    is_default: false, track_opens: true, track_clicks: true,
    created_at: '2025-10-01', updated_at: today },
  { id: 'email-prov-3', company_id: 'comp-1', provider: 'mailgun', display_name: 'Mailgun (Backup)',
    from_address: 'backup@aqari-erp.com', from_name: 'Aqari Backup',
    reply_to: '', status: 'inactive',
    api_key_masked: 'mg_••••••••7e2b', daily_quota: 5000, daily_sent: 0,
    is_default: false, track_opens: false, track_clicks: false,
    created_at: '2026-02-15', updated_at: today },
];

// ─────────────────────────────────────────────
// 4.3 Email Templates
// ─────────────────────────────────────────────
export const seedEmailTemplates: EmailTemplate[] = [
  { id: 'et-1', company_id: 'comp-1', name: 'فاتورة إيجار', category: 'invoice', language: 'ar',
    subject: 'فاتورة إيجار {{invoice_number}} - {{due_date}}',
    body_html: '<h2>مرحباً {{tenant_name}},</h2><p>فاتورة إيجار جديدة للوحدة <strong>{{unit_number}}</strong>.</p><table style="border-collapse:collapse"><tr><td>المبلغ:</td><td><strong>{{amount}} ر.ق</strong></td></tr><tr><td>تاريخ الاستحقاق:</td><td>{{due_date}}</td></tr></table><p><a href="{{payment_link}}">ادفع الآن</a></p>',
    body_text: 'مرحباً {{tenant_name}}، فاتورة إيجار {{invoice_number}} بمبلغ {{amount}} ر.ق. للاستحقاق في {{due_date}}. ادفع من: {{payment_link}}',
    variables: ['tenant_name', 'invoice_number', 'unit_number', 'amount', 'due_date', 'payment_link'],
    status: 'active', created_at: '2025-08-15', updated_at: today, notes: '' },
  { id: 'et-2', company_id: 'comp-1', name: 'إيصال استلام', category: 'receipt', language: 'ar',
    subject: 'إيصال استلام دفعة - {{receipt_number}}',
    body_html: '<h2>شكراً {{tenant_name}},</h2><p>تم استلام دفعتكم بمبلغ <strong>{{amount}} ر.ق</strong>.</p><p>رقم الإيصال: {{receipt_number}}<br>التاريخ: {{payment_date}}</p>',
    body_text: 'شكراً {{tenant_name}}، تم استلام {{amount}} ر.ق. الإيصال: {{receipt_number}}',
    variables: ['tenant_name', 'receipt_number', 'amount', 'payment_date'],
    status: 'active', created_at: '2025-08-15', updated_at: today, notes: '' },
  { id: 'et-3', company_id: 'comp-1', name: 'تنبيه تأخير', category: 'overdue_notice', language: 'ar',
    subject: 'تنبيه: دفعة إيجار متأخرة - {{invoice_number}}',
    body_html: '<h2>عزيزي {{tenant_name}},</h2><p style="color:red">دفعة الإيجار <strong>{{invoice_number}}</strong> متأخرة منذ {{days_overdue}} يوم.</p><p>يرجى السداد فوراً لتفادي الإجراءات القانونية.</p><p><a href="{{payment_link}}" style="background:#533afd;color:white;padding:10px 20px;text-decoration:none">ادفع الآن</a></p>',
    body_text: 'عزيزي {{tenant_name}}، الدفعة {{invoice_number}} متأخرة {{days_overdue}} يوم. ادفع من: {{payment_link}}',
    variables: ['tenant_name', 'invoice_number', 'days_overdue', 'payment_link'],
    status: 'active', created_at: '2025-08-20', updated_at: today, notes: '' },
  { id: 'et-4', company_id: 'comp-1', name: 'تجديد عقد', category: 'contract_renewal', language: 'ar',
    subject: 'تجديد عقد الإيجار {{contract_number}}',
    body_html: '<h2>عزيزي {{tenant_name}},</h2><p>عقد إيجاركم <strong>{{contract_number}}</strong> ينتهي في {{end_date}}.</p><p>لتجديد العقد برجاء التواصل معنا قبل {{notice_days}} يوم.</p>',
    body_text: 'عزيزي {{tenant_name}}، عقدكم {{contract_number}} ينتهي في {{end_date}}. يرجى التجديد قبل {{notice_days}} يوم.',
    variables: ['tenant_name', 'contract_number', 'end_date', 'notice_days'],
    status: 'active', created_at: '2025-09-01', updated_at: today, notes: '' },
  { id: 'et-5', company_id: 'comp-1', name: 'تحديث صيانة', category: 'maintenance_update', language: 'ar',
    subject: 'تحديث صيانة #{{request_id}} - {{status}}',
    body_html: '<h2>مرحباً {{tenant_name}},</h2><p>حالة طلب الصيانة <strong>#{{request_id}}</strong> تم تحديثها إلى: <strong>{{status}}</strong></p><p>{{notes}}</p>',
    body_text: 'طلب الصيانة {{request_id}} - {{status}}. {{notes}}',
    variables: ['tenant_name', 'request_id', 'status', 'notes'],
    status: 'active', created_at: '2025-09-15', updated_at: today, notes: '' },
  { id: 'et-6', company_id: 'comp-1', name: 'ترحيب بالمستأجر', category: 'lease_welcome', language: 'ar',
    subject: 'مرحباً بكم في عقاري ERP - {{tenant_name}}',
    body_html: '<h1>أهلاً وسهلاً {{tenant_name}}!</h1><p>نرحب بكم في عقاري. حساب البوابة الإلكترونية: <a href="{{portal_url}}">{{portal_url}}</a></p>',
    body_text: 'مرحباً {{tenant_name}}! حساب البوابة: {{portal_url}}',
    variables: ['tenant_name', 'portal_url'],
    status: 'active', created_at: '2025-10-01', updated_at: today, notes: '' },
];

// ─────────────────────────────────────────────
// 4.3 Email Messages
// ─────────────────────────────────────────────
export const seedEmailMessages: EmailMessage[] = [
  { id: 'em-1', company_id: 'comp-1', provider_id: 'email-prov-1', provider: 'resend',
    template_id: 'et-1', campaign_id: '',
    to_email: 'ahmed@email.com', to_name: 'أحمد محمد العمري',
    cc: '', bcc: '',
    subject: 'فاتورة إيجار INV-2026-001 - 2026-01-15',
    body_html: '<h2>مرحباً أحمد محمد العمري</h2><p>فاتورة إيجار للوحدة A-101 بمبلغ 60000 ر.ق</p>',
    attachments: '[]', status: 'opened',
    opened_count: 3, clicked_count: 1, open_rate: 60,
    gateway_message_id: 're_msg_4f8a2c1d',
    sent_at: '2026-01-01T08:00:00Z', delivered_at: '2026-01-01T08:00:02Z',
    opened_at: '2026-01-02T10:15:00Z', clicked_at: '2026-01-02T10:16:30Z',
    bounced_at: '', error_message: '',
    direction: 'outbound',
    related_entity_type: 'invoice', related_entity_id: 'inv-4',
    created_at: '2026-01-01T08:00:00Z' },
  { id: 'em-2', company_id: 'comp-1', provider_id: 'email-prov-1', provider: 'resend',
    template_id: 'et-2', campaign_id: '',
    to_email: 'ahmed@email.com', to_name: 'أحمد محمد العمري',
    cc: '', bcc: '',
    subject: 'إيصال استلام دفعة - RCP-2026-001',
    body_html: '<h2>شكراً أحمد</h2><p>تم استلام 60000 ر.ق</p>',
    attachments: '[]', status: 'opened',
    opened_count: 2, clicked_count: 0, open_rate: 100,
    gateway_message_id: 're_msg_4f8a2c1e',
    sent_at: '2026-01-10T08:14:40Z', delivered_at: '2026-01-10T08:14:42Z',
    opened_at: '2026-01-10T12:00:00Z', clicked_at: '',
    bounced_at: '', error_message: '',
    direction: 'outbound',
    related_entity_type: 'receipt', related_entity_id: 'rcp-1',
    created_at: '2026-01-10T08:14:40Z' },
  { id: 'em-3', company_id: 'comp-1', provider_id: 'email-prov-1', provider: 'resend',
    template_id: 'et-3', campaign_id: 'emc-1',
    to_email: 'fahad@email.com', to_name: 'فهد عبدالله الشمري',
    cc: 'legal@aqari-erp.com', bcc: '',
    subject: 'تنبيه: دفعة إيجار متأخرة - INV-2025-008',
    body_html: '<h2>عزيزي فهد</h2><p style="color:red">دفعة متأخرة 45 يوم</p>',
    attachments: '[]', status: 'bounced',
    opened_count: 0, clicked_count: 0, open_rate: 0,
    gateway_message_id: 're_msg_bounce_91',
    sent_at: '2026-05-20T10:00:00Z', delivered_at: '',
    opened_at: '', clicked_at: '',
    bounced_at: '2026-05-20T10:00:08Z',
    error_message: '5.1.1 Recipient address rejected: User unknown',
    direction: 'outbound',
    related_entity_type: 'invoice', related_entity_id: 'inv-4',
    created_at: '2026-05-20T10:00:00Z' },
  { id: 'em-4', company_id: 'comp-1', provider_id: 'email-prov-1', provider: 'resend',
    template_id: 'et-4', campaign_id: '',
    to_email: 'ahmed@email.com', to_name: 'أحمد محمد العمري',
    cc: '', bcc: '',
    subject: 'تجديد عقد الإيجار LSE-2025-001',
    body_html: '<h2>عزيزي أحمد</h2><p>عقدكم ينتهي قريباً</p>',
    attachments: '[]', status: 'clicked',
    opened_count: 5, clicked_count: 2, open_rate: 100,
    gateway_message_id: 're_msg_4f8a2c20',
    sent_at: '2026-05-25T09:00:00Z', delivered_at: '2026-05-25T09:00:02Z',
    opened_at: '2026-05-25T09:30:00Z', clicked_at: '2026-05-25T11:00:00Z',
    bounced_at: '', error_message: '',
    direction: 'outbound',
    related_entity_type: 'lease', related_entity_id: 'lse-1',
    created_at: '2026-05-25T09:00:00Z' },
  { id: 'em-5', company_id: 'comp-1', provider_id: 'email-prov-1', provider: 'resend',
    template_id: 'et-5', campaign_id: '',
    to_email: 'sara@email.com', to_name: 'سارة خالد القحطاني',
    cc: '', bcc: '',
    subject: 'تحديث صيانة #MNT-2026-008 - تم الإصلاح',
    body_html: '<h2>مرحباً سارة</h2><p>تم إصلاح التسرب بنجاح</p>',
    attachments: '[]', status: 'delivered',
    opened_count: 0, clicked_count: 0, open_rate: 0,
    gateway_message_id: 're_msg_4f8a2c21',
    sent_at: '2026-06-01T15:30:00Z', delivered_at: '2026-06-01T15:30:02Z',
    opened_at: '', clicked_at: '',
    bounced_at: '', error_message: '',
    direction: 'outbound',
    related_entity_type: 'maintenance', related_entity_id: 'mnt-2',
    created_at: '2026-06-01T15:30:00Z' },
];

// ─────────────────────────────────────────────
// 4.3 Email Campaigns
// ─────────────────────────────────────────────
export const seedEmailCampaigns: EmailCampaign[] = [
  { id: 'emc-1', company_id: 'comp-1', name: 'حملة المتأخرات - مايو 2026',
    template_id: 'et-3', audience_type: 'overdue_tenants', audience_count: 12,
    scheduled_at: '', sent_at: '2026-05-20T10:00:00Z',
    status: 'completed',
    delivered_count: 10, opened_count: 6, clicked_count: 3, bounced_count: 2,
    created_by: 'نورة الدوسري', created_at: '2026-05-19', notes: '' },
  { id: 'emc-2', company_id: 'comp-1', name: 'تجديد العقود - يونيو 2026',
    template_id: 'et-4', audience_type: 'all_tenants', audience_count: 5,
    scheduled_at: '', sent_at: '2026-05-25T09:00:00Z',
    status: 'completed',
    delivered_count: 5, opened_count: 5, clicked_count: 2, bounced_count: 0,
    created_by: 'سارة القحطاني', created_at: '2026-05-24', notes: '' },
  { id: 'emc-3', company_id: 'comp-1', name: 'النشرة الشهرية للمستأجرين',
    template_id: 'et-6', audience_type: 'all_tenants', audience_count: 5,
    scheduled_at: '2026-07-01T10:00:00Z', sent_at: '',
    status: 'scheduled',
    delivered_count: 0, opened_count: 0, clicked_count: 0, bounced_count: 0,
    created_by: 'محمد العتيبي', created_at: '2026-06-15', notes: 'نشرة يوليو 2026' },
];

// ─────────────────────────────────────────────
// 4.4 Push Providers
// ─────────────────────────────────────────────
export const seedPushProviders: PushProviderConfig[] = [
  { id: 'push-prov-1', company_id: 'comp-1', provider: 'onesignal', display_name: 'OneSignal (Web)',
    status: 'active', app_id: 'os_app_a4f2c1d8', api_key_masked: 'os_••••••••91c8',
    sender_id: '', whatsapp_phone_number: '', whatsapp_business_id: '', whatsapp_token_masked: '',
    is_default: true, created_at: '2025-08-15', updated_at: today },
  { id: 'push-prov-2', company_id: 'comp-1', provider: 'fcm', display_name: 'Firebase (Mobile)',
    status: 'active', app_id: '1:1234:android:abcd', api_key_masked: 'AAAA•••••xyz:APA91b',
    sender_id: '1234567890', whatsapp_phone_number: '', whatsapp_business_id: '', whatsapp_token_masked: '',
    is_default: false, created_at: '2025-09-01', updated_at: today },
  { id: 'push-prov-3', company_id: 'comp-1', provider: 'whatsapp_business', display_name: 'WhatsApp Business',
    status: 'active', app_id: '', api_key_masked: '',
    sender_id: '', whatsapp_phone_number: '+97444001122',
    whatsapp_business_id: 'waba_8821', whatsapp_token_masked: 'EAA•••••a4f2',
    is_default: false, created_at: '2025-11-15', updated_at: today },
];

// ─────────────────────────────────────────────
// 4.4 Push Subscribers
// ─────────────────────────────────────────────
export const seedPushSubscribers: PushSubscriber[] = [
  { id: 'sub-1', company_id: 'comp-1', user_identifier: 'ahmed@email.com',
    name: 'أحمد محمد العمري', email: 'ahmed@email.com', phone: '+97450001122',
    device_type: 'web', device_model: 'Chrome / Windows 11', app_version: '1.0.0',
    language: 'ar', timezone: 'Asia/Riyadh', subscribed: true,
    opt_in_date: '2025-09-15', last_seen_at: '2026-06-02T08:00:00Z',
    tags_json: '{"tenant":true,"property":"prop-1"}',
    total_received: 24, total_opened: 18, created_at: '2025-09-15' },
  { id: 'sub-2', company_id: 'comp-1', user_identifier: 'sara@email.com',
    name: 'سارة خالد القحطاني', email: 'sara@email.com', phone: '+97450002233',
    device_type: 'android', device_model: 'iPhone 14 Pro', app_version: '2.1.0',
    language: 'ar', timezone: 'Asia/Riyadh', subscribed: true,
    opt_in_date: '2025-10-01', last_seen_at: '2026-06-01T20:00:00Z',
    tags_json: '{"tenant":true,"property":"prop-1"}',
    total_received: 18, total_opened: 16, created_at: '2025-10-01' },
  { id: 'sub-3', company_id: 'comp-1', user_identifier: '+97450003344',
    name: 'شركة النور التجارية', email: 'info@alnoor.com', phone: '+97450003344',
    device_type: 'android', device_model: 'Samsung Galaxy S24', app_version: '2.1.0',
    language: 'ar', timezone: 'Asia/Riyadh', subscribed: true,
    opt_in_date: '2025-10-20', last_seen_at: '2026-05-30T14:00:00Z',
    tags_json: '{"tenant":true,"property":"prop-2","business":true}',
    total_received: 12, total_opened: 8, created_at: '2025-10-20' },
  { id: 'sub-4', company_id: 'comp-1', user_identifier: 'fahad@email.com',
    name: 'فهد عبدالله الشمري', email: 'fahad@email.com', phone: '+97450004455',
    device_type: 'android', device_model: 'iPhone 13', app_version: '2.0.5',
    language: 'ar', timezone: 'Asia/Riyadh', subscribed: false,
    opt_in_date: '2025-08-01', last_seen_at: '2026-05-15T12:00:00Z',
    tags_json: '{"tenant":true,"property":"prop-1"}',
    total_received: 8, total_opened: 3, created_at: '2025-08-01' },
  { id: 'sub-5', company_id: 'comp-1', user_identifier: 'noura@email.com',
    name: 'نورة سعد الدوسري', email: 'noura@email.com', phone: '+97450005566',
    device_type: 'web', device_model: 'Safari / iPad', app_version: '1.0.0',
    language: 'ar', timezone: 'Asia/Riyadh', subscribed: true,
    opt_in_date: '2025-12-01', last_seen_at: '2026-05-28T10:00:00Z',
    tags_json: '{"tenant":true,"property":"prop-1"}',
    total_received: 5, total_opened: 4, created_at: '2025-12-01' },
];

// ─────────────────────────────────────────────
// 4.4 Push Campaigns
// ─────────────────────────────────────────────
export const seedPushCampaigns: PushCampaign[] = [
  { id: 'pc-1', company_id: 'comp-1', name: 'تذكير دفع الإيجار - يونيو',
    provider: 'onesignal', audience_type: 'all', audience_tags: 'tenant=true',
    audience_count: 4, title: 'تذكير دفع الإيجار',
    body: 'دفعة إيجار شهر يونيو مستحقة. ادفع من تطبيقك.',
    icon_url: '/icons/rent.png', image_url: '', action_url: '/invoices',
    scheduled_at: '', sent_at: '2026-06-01T08:00:00Z',
    status: 'completed', delivered_count: 4, opened_count: 3, failed_count: 0,
    created_by: 'محمد العتيبي', created_at: '2026-05-30', notes: '' },
  { id: 'pc-2', company_id: 'comp-1', name: 'إعلان صيانة المصاعد',
    provider: 'whatsapp_business', audience_type: 'all', audience_tags: '',
    audience_count: 5, title: 'صيانة المصاعد',
    body: 'سيتم صيانة المصاعد يوم 20 يونيو من 9ص-3م. نعتذر عن الإزعاج.',
    icon_url: '', image_url: '', action_url: '',
    scheduled_at: '2026-06-15T10:00:00Z', sent_at: '',
    status: 'scheduled', delivered_count: 0, opened_count: 0, failed_count: 0,
    created_by: 'سارة القحطاني', created_at: '2026-06-10', notes: '' },
  { id: 'pc-3', company_id: 'comp-1', name: 'تحديث الصيانة - B-201',
    provider: 'fcm', audience_type: 'tag_segment', audience_tags: 'property=prop-2',
    audience_count: 1, title: 'تحديث الصيانة',
    body: 'تم إصلاح تسرب المياه في وحدتكم. شكراً لصبركم.',
    icon_url: '', image_url: '', action_url: '/maintenance/MNT-2026-014',
    scheduled_at: '', sent_at: '2026-05-25T16:00:00Z',
    status: 'completed', delivered_count: 1, opened_count: 1, failed_count: 0,
    created_by: 'فني أحمد', created_at: '2026-05-25', notes: '' },
];

// ─────────────────────────────────────────────
// 4.5 E-Sign Providers
// ─────────────────────────────────────────────
export const seedESignProviders: ESignProviderConfig[] = [
  { id: 'es-prov-1', company_id: 'comp-1', provider: 'docusign', display_name: 'DocuSign (Primary)',
    status: 'active', api_key_masked: 'ds_live_••••••••a4f2',
    account_id: 'ds_acc_8821', webhook_secret_masked: 'whsec_••••••••91c8',
    supports_arabic: true, is_default: true,
    created_at: '2025-08-15', updated_at: today },
  { id: 'es-prov-2', company_id: 'comp-1', provider: 'zoho_sign', display_name: 'Zoho Sign (MENA)',
    status: 'active', api_key_masked: 'zo_••••••••3d9e',
    account_id: 'zoho_acc_4421', webhook_secret_masked: 'whsec_••••••••b2a1',
    supports_arabic: true, is_default: false,
    created_at: '2025-10-20', updated_at: today },
  { id: 'es-prov-3', company_id: 'comp-1', provider: 'pandadoc', display_name: 'PandaDoc',
    status: 'inactive', api_key_masked: 'pd_test_••••••••1f7c',
    account_id: 'pd_acc_001', webhook_secret_masked: 'whsec_••••••••44de',
    supports_arabic: true, is_default: false,
    created_at: '2026-01-05', updated_at: today },
];

// ─────────────────────────────────────────────
// 4.5 E-Sign Documents
// ─────────────────────────────────────────────
export const seedESignDocuments: ESignDocument[] = [
  { id: 'esd-1', company_id: 'comp-1', provider_id: 'es-prov-1', provider: 'docusign',
    document_name: 'عقد إيجار - أحمد العمري - A-101', document_type: 'lease',
    file_url: '/uploads/leases/lse-1.pdf', file_size_kb: 245, page_count: 8,
    status: 'completed', related_entity_type: 'lease', related_entity_id: 'lse-1',
    signer_count: 2, signed_count: 2, declined_count: 0,
    created_by: 'نورة الدوسري', created_at: '2025-01-01', updated_at: '2025-01-02',
    completed_at: '2025-01-02T10:30:00Z', expires_at: '2025-02-01',
    notes: 'تم التوقيع الإلكتروني بنجاح' },
  { id: 'esd-2', company_id: 'comp-1', provider_id: 'es-prov-1', provider: 'docusign',
    document_name: 'عقد إيجار - سارة القحطاني - A-102', document_type: 'lease',
    file_url: '/uploads/leases/lse-2.pdf', file_size_kb: 245, page_count: 8,
    status: 'in_progress', related_entity_type: 'lease', related_entity_id: 'lse-2',
    signer_count: 2, signed_count: 1, declined_count: 0,
    created_by: 'نورة الدوسري', created_at: '2025-02-25', updated_at: '2025-02-26',
    completed_at: '', expires_at: '2026-06-30',
    notes: 'بانتظار توقيع المستأجر' },
  { id: 'esd-3', company_id: 'comp-1', provider_id: 'es-prov-2', provider: 'zoho_sign',
    document_name: 'تجديد عقد - فهد الشمري - A-301', document_type: 'lease',
    file_url: '/uploads/leases/lse-4-renewal.pdf', file_size_kb: 245, page_count: 8,
    status: 'sent', related_entity_type: 'lease', related_entity_id: 'lse-4',
    signer_count: 2, signed_count: 0, declined_count: 0,
    created_by: 'سارة القحطاني', created_at: '2026-05-20', updated_at: '2026-05-20',
    completed_at: '', expires_at: '2026-06-20',
    notes: 'بانتظار المراجعة' },
  { id: 'esd-4', company_id: 'comp-1', provider_id: 'es-prov-1', provider: 'docusign',
    document_name: 'اتفاقية صيانة - B-201', document_type: 'service',
    file_url: '/uploads/contracts/maint-b201.pdf', file_size_kb: 120, page_count: 4,
    status: 'draft', related_entity_type: 'workorder', related_entity_id: 'wo-3',
    signer_count: 2, signed_count: 0, declined_count: 0,
    created_by: 'فني أحمد', created_at: today, updated_at: today,
    completed_at: '', expires_at: '2026-07-15',
    notes: 'مسودة - لم يتم الإرسال بعد' },
  { id: 'esd-5', company_id: 'comp-1', provider_id: 'es-prov-1', provider: 'docusign',
    document_name: 'NDA - شركة النور', document_type: 'nda',
    file_url: '/uploads/legal/nda-alnoor.pdf', file_size_kb: 95, page_count: 3,
    status: 'declined', related_entity_type: 'tenant', related_entity_id: 'tnt-3',
    signer_count: 2, signed_count: 0, declined_count: 1,
    created_by: 'محمد العتيبي', created_at: '2026-04-15', updated_at: '2026-04-18',
    completed_at: '', expires_at: '2026-05-15',
    notes: 'مرفوض من قبل المستأجر - يحتاج مراجعة' },
];

// ─────────────────────────────────────────────
// 4.5 E-Sign Signers
// ─────────────────────────────────────────────
export const seedESignSigners: ESignSigner[] = [
  { id: 'ess-1', document_id: 'esd-1', signer_order: 1, name: 'أحمد محمد العمري',
    email: 'ahmed@email.com', phone: '+97450001122', role: 'tenant', status: 'signed',
    signed_at: '2025-01-02T10:15:00Z', signature_url: '/signatures/ahmed-ess-1.png',
    ip_address: '188.50.12.44', user_agent: 'Mozilla/5.0...',
    sent_at: '2025-01-01T08:00:00Z', viewed_at: '2025-01-02T10:00:00Z' },
  { id: 'ess-2', document_id: 'esd-1', signer_order: 2, name: 'د. محمد العتيبي',
    email: 'mohammed@aqari-erp.com', phone: '+97444001122', role: 'landlord', status: 'signed',
    signed_at: '2025-01-02T10:30:00Z', signature_url: '/signatures/mohammed-ess-2.png',
    ip_address: '188.50.1.1', user_agent: 'Mozilla/5.0...',
    sent_at: '2025-01-01T08:00:00Z', viewed_at: '2025-01-02T10:15:00Z' },
  { id: 'ess-3', document_id: 'esd-2', signer_order: 1, name: 'د. محمد العتيبي',
    email: 'mohammed@aqari-erp.com', phone: '+97444001122', role: 'landlord', status: 'signed',
    signed_at: '2025-02-25T14:00:00Z', signature_url: '/signatures/mohammed-ess-3.png',
    ip_address: '188.50.1.1', user_agent: 'Mozilla/5.0...',
    sent_at: '2025-02-25T08:00:00Z', viewed_at: '2025-02-25T13:00:00Z' },
  { id: 'ess-4', document_id: 'esd-2', signer_order: 2, name: 'سارة خالد القحطاني',
    email: 'sara@email.com', phone: '+97450002233', role: 'tenant', status: 'sent',
    signed_at: '', signature_url: '',
    ip_address: '', user_agent: '',
    sent_at: '2025-02-25T14:05:00Z', viewed_at: '' },
  { id: 'ess-5', document_id: 'esd-3', signer_order: 1, name: 'د. محمد العتيبي',
    email: 'mohammed@aqari-erp.com', phone: '+97444001122', role: 'landlord', status: 'signed',
    signed_at: '2026-05-20T10:00:00Z', signature_url: '/signatures/mohammed-ess-5.png',
    ip_address: '188.50.1.1', user_agent: 'Mozilla/5.0...',
    sent_at: '2026-05-20T09:00:00Z', viewed_at: '2026-05-20T09:30:00Z' },
  { id: 'ess-6', document_id: 'esd-3', signer_order: 2, name: 'فهد عبدالله الشمري',
    email: 'fahad@email.com', phone: '+97450004455', role: 'tenant', status: 'sent',
    signed_at: '', signature_url: '',
    ip_address: '', user_agent: '',
    sent_at: '2026-05-20T10:05:00Z', viewed_at: '' },
  { id: 'ess-7', document_id: 'esd-5', signer_order: 1, name: 'د. محمد العتيبي',
    email: 'mohammed@aqari-erp.com', phone: '+97444001122', role: 'landlord', status: 'signed',
    signed_at: '2026-04-15T11:00:00Z', signature_url: '/signatures/mohammed-ess-7.png',
    ip_address: '188.50.1.1', user_agent: 'Mozilla/5.0...',
    sent_at: '2026-04-15T10:00:00Z', viewed_at: '2026-04-15T10:30:00Z' },
  { id: 'ess-8', document_id: 'esd-5', signer_order: 2, name: 'خالد النوري',
    email: 'info@alnoor.com', phone: '+97450003344', role: 'tenant', status: 'declined',
    signed_at: '', signature_url: '',
    ip_address: '188.50.45.78', user_agent: 'Mozilla/5.0...',
    sent_at: '2026-04-15T11:05:00Z', viewed_at: '2026-04-18T09:00:00Z' },
];

// ─────────────────────────────────────────────
// 4.5 E-Sign Requests
// ─────────────────────────────────────────────
export const seedESignRequests: ESignRequest[] = [
  { id: 'esr-1', company_id: 'comp-1', document_id: 'esd-1',
    subject: 'يرجى التوقيع على عقد الإيجار', message: 'مرحباً أحمد، مرفق عقد إيجار وحدتكم. يرجى المراجعة والتوقيع.',
    status: 'completed', initiated_by: 'نورة الدوسري',
    sent_at: '2025-01-01T08:00:00Z', completed_at: '2025-01-02T10:30:00Z',
    expires_at: '2025-02-01', reminder_count: 1, last_reminder_at: '2025-01-02T08:00:00Z',
    certificate_url: '/certificates/esr-1.pdf', audit_trail_url: '/audit/esr-1.pdf',
    notes: '' },
  { id: 'esr-2', company_id: 'comp-1', document_id: 'esd-2',
    subject: 'يرجى التوقيع على عقد الإيجار', message: 'مرحباً سارة، مرفق عقد إيجار وحدتكم.',
    status: 'signed', initiated_by: 'نورة الدوسري',
    sent_at: '2025-02-25T08:00:00Z', completed_at: '',
    expires_at: '2026-06-30', reminder_count: 2, last_reminder_at: '2026-05-15T08:00:00Z',
    certificate_url: '', audit_trail_url: '/audit/esr-2.pdf',
    notes: 'بانتظار توقيع المستأجر - تم إرسال تذكيرين' },
  { id: 'esr-3', company_id: 'comp-1', document_id: 'esd-3',
    subject: 'تجديد عقد الإيجار', message: 'مرحباً فهد، يرجى التوقيع على تجديد العقد.',
    status: 'sent', initiated_by: 'سارة القحطاني',
    sent_at: '2026-05-20T09:00:00Z', completed_at: '',
    expires_at: '2026-06-20', reminder_count: 0, last_reminder_at: '',
    certificate_url: '', audit_trail_url: '',
    notes: 'بانتظار توقيع المستأجر' },
  { id: 'esr-4', company_id: 'comp-1', document_id: 'esd-5',
    subject: 'اتفاقية عدم إفصاح', message: 'مرحباً، يرجى التوقيع على اتفاقية NDA.',
    status: 'declined', initiated_by: 'محمد العتيبي',
    sent_at: '2026-04-15T10:00:00Z', completed_at: '2026-04-18T09:00:00Z',
    expires_at: '2026-05-15', reminder_count: 0, last_reminder_at: '',
    certificate_url: '', audit_trail_url: '/audit/esr-4.pdf',
    notes: 'مرفوض - يحتاج مراجعة قانونية' },
];

// ─────────────────────────────────────────────
// 4.5 E-Sign Audit Events
// ─────────────────────────────────────────────
export const seedESignAuditEvents: ESignAuditEvent[] = [
  { id: 'esae-1', document_id: 'esd-1', request_id: 'esr-1',
    event_type: 'document_created', actor_email: 'noura@aqari-erp.com',
    actor_name: 'نورة الدوسري', ip_address: '188.50.1.10',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0)', event_at: '2025-01-01T07:45:00Z',
    event_hash: 'a4f2c1d8...', previous_hash: '00000000...',
    details: 'تم إنشاء المستند في النظام' },
  { id: 'esae-2', document_id: 'esd-1', request_id: 'esr-1',
    event_type: 'document_sent', actor_email: 'noura@aqari-erp.com',
    actor_name: 'نورة الدوسري', ip_address: '188.50.1.10',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0)', event_at: '2025-01-01T08:00:00Z',
    event_hash: '91c8b2a1...', previous_hash: 'a4f2c1d8...',
    details: 'تم إرسال الطلب إلى المستأجر والمالك' },
  { id: 'esae-3', document_id: 'esd-1', request_id: 'esr-1',
    event_type: 'document_viewed', actor_email: 'ahmed@email.com',
    actor_name: 'أحمد محمد العمري', ip_address: '188.50.12.44',
    user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0)', event_at: '2025-01-02T10:00:00Z',
    event_hash: '3d9e44de...', previous_hash: '91c8b2a1...',
    details: 'قام المستأجر بفتح المستند' },
  { id: 'esae-4', document_id: 'esd-1', request_id: 'esr-1',
    event_type: 'document_signed', actor_email: 'ahmed@email.com',
    actor_name: 'أحمد محمد العمري', ip_address: '188.50.12.44',
    user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0)', event_at: '2025-01-02T10:15:00Z',
    event_hash: '1f7ccc52...', previous_hash: '3d9e44de...',
    details: 'توقيع المستأجر - قيمة: 5,200.00 ر.ق' },
  { id: 'esae-5', document_id: 'esd-1', request_id: 'esr-1',
    event_type: 'document_completed', actor_email: 'system',
    actor_name: 'النظام', ip_address: '127.0.0.1',
    user_agent: 'DocuSign-Webhook/1.0', event_at: '2025-01-02T10:30:00Z',
    event_hash: '88ae6f1c...', previous_hash: '1f7ccc52...',
    details: 'اكتمل توقيع جميع الأطراف - 2 من 2' },
  { id: 'esae-6', document_id: 'esd-1', request_id: 'esr-1',
    event_type: 'certificate_generated', actor_email: 'system',
    actor_name: 'النظام', ip_address: '127.0.0.1',
    user_agent: 'DocuSign-Webhook/1.0', event_at: '2025-01-02T10:30:30Z',
    event_hash: '42de1c8b...', previous_hash: '88ae6f1c...',
    details: 'تم إنشاء شهادة التوقيع الإلكتروني' },
  { id: 'esae-7', document_id: 'esd-5', request_id: 'esr-4',
    event_type: 'document_declined', actor_email: 'info@alnoor.com',
    actor_name: 'خالد النوري', ip_address: '188.50.45.78',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0)', event_at: '2026-04-18T09:00:00Z',
    event_hash: 'cc521f7c...', previous_hash: 'a4f291c8...',
    details: 'مرفوض - السبب: بند 5 يحتاج مراجعة' },
];
